// bini-export/src/index.ts
// Produces a pure static SPA build — strips all bini-router platform entry
// files after vite build so your dist/ folder contains only the SPA shell.
// Also pre-renders each route as its own index.html for GitHub Pages.
//
// ─── Setup ───────────────────────────────────────────────────────────────────
//
//   vite.config.ts
//     import { biniExport } from 'bini-export'
//     plugins: [react(), biniroute({ platform: 'netlify' }), biniExport()]
//
//   package.json
//     "export": "vite build --mode export"
//
// ─── Usage ───────────────────────────────────────────────────────────────────
//
//   pnpm build   →  normal build  (platform entry generated as usual)
//   pnpm export  →  static export (platform entry deleted, per-route HTML generated)
//
// ─────────────────────────────────────────────────────────────────────────────

import fs   from 'node:fs'
import path from 'node:path'
import type { Plugin, ResolvedConfig } from 'vite'

// ─── Types ───────────────────────────────────────────────────────────────────

export interface BiniExportOptions {
  /**
   * Extra file/directory paths to delete after the static export build,
   * relative to the project root.
   * @default []
   */
  cleanPaths?: string[]

  /**
   * Vite mode that activates the plugin.
   * @default 'export'
   */
  mode?: string

  /**
   * Generate a 404.html that redirects to the correct pre-rendered page.
   * If src/app/not-found.tsx (or .jsx/.ts/.js) exists, that page's built
   * HTML is used instead of the default redirect template.
   * @default true
   */
  copy404?: boolean

  /**
   * Pre-render each discovered route as its own index.html.
   * This eliminates the need for basename on BrowserRouter and
   * makes GitHub Pages serve each page directly.
   * @default true
   */
  prerender?: boolean
}

// ─── Constants ───────────────────────────────────────────────────────────────

// All known platform entry files generated by bini-router
const BINI_ROUTER_GENERATED: string[] = [
  'netlify/edge-functions/api.ts',  // netlify
  'worker.ts',                       // cloudflare
  'server/index.ts',                 // node / deno / bun
  'server/index.js',
  'handler.ts',                      // aws
  'handler.js',
  'api/index.ts',                    // vercel
  'api/index.js',
]

const NOT_FOUND_EXTS = ['.tsx', '.jsx', '.ts', '.js'] as const

// ANSI color helpers — consistent across all log messages
const C = {
  cyan  : (s: string) => `\x1b[36m${s}\x1b[0m`,
  green : (s: string) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s: string) => `\x1b[33m${s}\x1b[0m`,
  dim   : (s: string) => `\x1b[2m${s}\x1b[0m`,
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function findNotFoundFile(root: string): string | null {
  for (const ext of NOT_FOUND_EXTS) {
    const f = path.join(root, `src/app/not-found${ext}`)
    if (fs.existsSync(f)) return f
  }
  return null
}

function normBase(base: string): string {
  // Ensure base has a leading slash and no trailing slash
  // e.g. '/my-repo/' → '/my-repo', '/' → ''
  const b = base.startsWith('/') ? base : `/${base}`
  return b === '/' ? '' : b.replace(/\/$/, '')
}

// ─── Route Scanner ────────────────────────────────────────────────────────────
// Reads the auto-generated App.tsx/App.jsx to extract static route paths.
// Matches ALL path="..." attributes on <Route> elements — handles both
// direct routes and routes nested inside layout chains.
// Skips dynamic (:param) and catch-all (*) routes.

function scanRoutesFromAppFile(root: string): string[] {
  const candidates = [
    path.join(root, 'src/App.tsx'),
    path.join(root, 'src/App.jsx'),
  ]

  let src = ''
  for (const f of candidates) {
    if (fs.existsSync(f)) { src = fs.readFileSync(f, 'utf8'); break }
  }
  if (!src) return ['/']

  const routes = new Set<string>(['/'])

  // Match path="..." on <Route> elements
  // Handles both direct routes and routes nested inside layout chains
  const re = /\bpath=["']([^"']+)["']/g
  let m: RegExpExecArray | null
  while ((m = re.exec(src)) !== null) {
    const p = m[1]?.trim()
    if (!p) continue
    // Skip dynamic routes (:param), catch-all (*), and root (already added)
    if (p === '*' || p === '/') continue
    if (p.includes(':') || p.includes('*')) continue
    routes.add(p.startsWith('/') ? p : `/${p}`)
  }

  return [...routes].sort()
}

// ─── 404.html template ───────────────────────────────────────────────────────

function generate404(base: string): string {
  const cleanBase = normBase(base)
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Redirecting…</title>
<script>
// bini-export: 404 redirect for GitHub Pages SPA routing
var base = '${cleanBase}';
var path = location.pathname.replace(base, '') + location.search + location.hash;
if (!path || path === base) path = '/';
sessionStorage.setItem('__bini_spa_redirect', path);
location.replace((base || '') + '/');
</script>
</head>
<body></body>
</html>`
}

// Injected into index.html <head> — receives the redirect and restores the path
const REDIRECT_RECEIVER = `<script>
// bini-export: restore path after GitHub Pages 404 redirect
;(function(){
  var redirect = sessionStorage.getItem('__bini_spa_redirect')
  if (redirect) {
    sessionStorage.removeItem('__bini_spa_redirect')
    history.replaceState(null, '', redirect)
  }
})()
</script>`

// ─── Prune empty parent directories ──────────────────────────────────────────

function pruneEmptyDirs(root: string, filePath: string, logger: ResolvedConfig['logger']): void {
  let current = path.resolve(root, path.dirname(filePath))
  // Walk up until we hit the project root or a non-empty directory
  while (current !== root && current !== path.dirname(current)) {
    try {
      if (!fs.existsSync(current)) break
      const entries = fs.readdirSync(current)
      if (entries.length > 0) break
      fs.rmdirSync(current)
      logger.info(`  ${C.green('➜')}  removed empty dir ${C.dim(path.relative(root, current))}`)
      current = path.dirname(current)
    } catch {
      break
    }
  }
}

// ─── Plugin ──────────────────────────────────────────────────────────────────

export function biniExport(opts: BiniExportOptions = {}): Plugin {
  const {
    cleanPaths: extraPaths = [],
    mode: targetMode       = 'export',
    copy404                = true,
    prerender              = true,
  } = opts

  const pathsToClean = [...BINI_ROUTER_GENERATED, ...extraPaths]

  let cfg      : ResolvedConfig
  let isExport : boolean = false

  // ── helpers ────────────────────────────────────────────────────────────────

  function tryRemove(abs: string, rel: string): boolean {
    try {
      if (!fs.existsSync(abs)) return false
      fs.rmSync(abs, { recursive: true, force: true })
      cfg.logger.info(`  ${C.green('➜')}  removed ${C.dim(rel)}`)
      return true
    } catch (err) {
      cfg.logger.warn(`  ${C.yellow('⚠')}  could not remove ${rel}: ${(err as Error).message}`)
      return false
    }
  }

  // ── plugin object ──────────────────────────────────────────────────────────

  return {
    name   : 'vite-plugin-bini-export',
    enforce: 'post',

    configResolved(resolved) {
      cfg      = resolved
      isExport = resolved.mode === targetMode

      if (isExport) {
        cfg.logger.info(`\n  ${C.cyan('ß bini-export')} static export mode\n`)
      }
    },

    transformIndexHtml: {
      order: 'pre',
      handler(html) {
        // Only inject redirect receiver when pre-rendering is active
        if (!isExport || !prerender) return html
        return html.replace(/<head([^>]*)>/i, (m) => m + '\n    ' + REDIRECT_RECEIVER)
      },
    },

    async closeBundle() {
      if (!isExport || cfg.command !== 'build') return

      const base   = cfg.base || '/'
      const outDir = path.resolve(cfg.root, cfg.build.outDir)

      // Guard — if dist/index.html doesn't exist the build likely failed
      const indexPath = path.join(outDir, 'index.html')
      if (!fs.existsSync(indexPath)) {
        cfg.logger.warn(
          `  ${C.yellow('⚠')}  dist/index.html not found — the build may have failed`
        )
        return
      }

      const indexHtml = fs.readFileSync(indexPath, 'utf8')

      // ── 1. Pre-render each static route ────────────────────────────────────
      if (prerender) {
        const routes = scanRoutesFromAppFile(cfg.root)

        cfg.logger.info(`\n  ${C.cyan('ß bini-export')} pre-rendering ${C.green(String(routes.length))} route(s)`)

        for (const route of routes) {
          if (route === '/') continue

          const routeDir  = path.join(outDir, route.replace(/^\//, ''))
          const routeFile = path.join(routeDir, 'index.html')

          try {
            fs.mkdirSync(routeDir, { recursive: true })
            fs.writeFileSync(routeFile, indexHtml, 'utf8')
            cfg.logger.info(
              `  ${C.green('➜')}  ${route} ${C.dim('→')} ${C.cyan(path.relative(cfg.root, routeFile))}`
            )
          } catch (err) {
            cfg.logger.warn(
              `  ${C.yellow('⚠')}  failed to pre-render ${route}: ${(err as Error).message}`
            )
          }
        }
      }

      // ── 2. Generate 404.html ────────────────────────────────────────────────
      if (copy404) {
        const dest              = path.join(outDir, '404.html')
        const hasCustomNotFound = findNotFoundFile(cfg.root) !== null

        try {
          if (hasCustomNotFound) {
            // User has not-found.tsx — copy index.html as 404.html so
            // GitHub Pages boots the SPA and React Router renders the custom page
            fs.writeFileSync(dest, indexHtml, 'utf8')
            cfg.logger.info(
              `  ${C.green('➜')}  404.html ${C.dim('←')} custom not-found ${C.cyan(path.relative(cfg.root, dest))}`
            )
          } else {
            // No custom not-found — use the default redirect template
            fs.writeFileSync(dest, generate404(base), 'utf8')
            cfg.logger.info(
              `  ${C.green('➜')}  404.html ${C.dim('←')} redirect template ${C.cyan(path.relative(cfg.root, dest))}`
            )
          }
        } catch (err) {
          cfg.logger.warn(
            `  ${C.yellow('⚠')}  failed to write 404.html: ${(err as Error).message}`
          )
        }
      }

      // ── 3. Remove platform entry files ─────────────────────────────────────
      let removed = 0
      for (const rel of pathsToClean) {
        const abs = path.resolve(cfg.root, rel)
        if (tryRemove(abs, rel)) {
          pruneEmptyDirs(cfg.root, rel, cfg.logger)
          removed++
        }
      }

      if (removed === 0) {
        cfg.logger.info(
          `\n  ${C.cyan('ß bini-export')} dist/ is already clean\n`
        )
      } else {
        cfg.logger.info(
          `\n  ${C.cyan('ß bini-export')} export complete — ` +
          `${C.green(String(removed))} file(s) removed\n`
        )
      }
    },
  }
}